"""s04 rbac: users / role_assignments / permission_overrides

Revision ID: 87cb868be9fc
Revises: dbf5149a383f
Create Date: 2026-06-12 00:18:54.403316

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "87cb868be9fc"
down_revision: str | Sequence[str] | None = "dbf5149a383f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permission_overrides",
        sa.Column("override_id", sa.String(length=64), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("resource", sa.String(length=32), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("effect", sa.String(length=16), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("tenant_id", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("override_id"),
        sa.UniqueConstraint(
            "tenant_id", "role", "resource", "action", name="uq_overrides_tenant_cell"
        ),
    )
    op.create_index("idx_overrides_tenant", "permission_overrides", ["tenant_id"], unique=False)
    op.create_index(
        "idx_overrides_tenant_role", "permission_overrides", ["tenant_id", "role"], unique=False
    )
    op.create_table(
        "role_assignments",
        sa.Column("assignment_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("tenant_id", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("assignment_id"),
        sa.UniqueConstraint("tenant_id", "user_id", "role", name="uq_assignments_tenant_user_role"),
    )
    op.create_index("idx_assignments_tenant", "role_assignments", ["tenant_id"], unique=False)
    op.create_index(
        "idx_assignments_tenant_user", "role_assignments", ["tenant_id", "user_id"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("tenant_id", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "email", name="uq_users_tenant_email"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index("idx_users_tenant", "users", ["tenant_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_users_tenant", table_name="users")
    op.drop_table("users")
    op.drop_index("idx_assignments_tenant_user", table_name="role_assignments")
    op.drop_index("idx_assignments_tenant", table_name="role_assignments")
    op.drop_table("role_assignments")
    op.drop_index("idx_overrides_tenant_role", table_name="permission_overrides")
    op.drop_index("idx_overrides_tenant", table_name="permission_overrides")
    op.drop_table("permission_overrides")
    # ### end Alembic commands ###
